"Freenas 11.3 Setup.md" :
	m4 "bin/bazarr.m4" > "bazarr.rc"
	m4 "bin/bazarr_setup.m4" > "bazarr_setup.sh"
	m4 "bin/deluge_setup.m4" > "deluge_setup.sh"
	m4 "bin/deluge_VPN_setup.m4" > "deluge_add_VPN.sh"
	m4 "bin/jackett.m4" > "jackett.rc"
	m4 "bin/jackett_setup.m4" > "jackett_setup.sh"
	m4 "bin/lidarr.m4" > "lidarr.rc"
	m4 "bin/lidarr_setup.m4" > "lidarr_setup.sh"
	m4 "bin/organizr_nginx.m4" > "organizr_nginx.conf"
	m4 "bin/organizr_setup.m4" > "organizr_setup.sh"
	m4 "bin/plex_setup.m4" > "plex_setup.sh"
	m4 "bin/radarr.m4" > "radarr.rc"
	m4 "bin/radarr_setup.m4" > "radarr_setup.sh"
	m4 "bin/sabnzbd_setup.m4" > "sabnzbd_setup.sh"
	m4 "bin/sonarr.m4" > "sonarr.rc"
	m4 "bin/sonarr_setup.m4" > "sonarr_setup.sh"
	m4 "bin/tautulli_setup.m4" > "tautulli_setup.sh"
	m4 "bin/transmission_setup.m4" > "transmission_setup.sh"
	m4 "bin/transmission_VPN_setup.m4" > "transmission_add_VPN.sh"
	m4 "bin/torrent_ipfw.m4" > torrent_ipfw.rules
	m4 "bin/Freenas 11.3 Setup.m4" > "Freenas 11.3 Setup.md"

clean :
	rm "Freenas 11.3 Setup.md"
	rm "bazarr.rc"
	rm "bazarr_setup.sh"
	rm "deluge_setup.sh"
	rm "deluge_add_VPN.sh"
	rm "jackett.rc"
	rm "jackett_setup.sh"
	rm "lidarr.rc"
	rm "lidarr_setup.sh"
	rm "organizr_setup.sh"
	rm "organizr_nginx.conf"
	rm "plex_setup.sh"
	rm "radarr.rc"
	rm "radarr_setup.sh"
	rm "sabnzbd_setup.sh"
	rm "sonarr.rc"
	rm "sonarr_setup.sh"
	rm "tautulli_setup.sh"
	rm "transmission_setup.sh"
	rm "transmission_add_VPN.sh"
	rm "torrent_ipfw.rules"
