"Freenas 11.3 Setup.md" :
	m4 "bin/bazarr_setup.m4" > "bazarr_setup.sh"
	m4 "bin/emby_setup.m4" > "emby_setup.sh"
	m4 "bin/jellyfin_setup.m4" > "jellyfin_setup.sh"
	m4 "bin/lidarr_setup.m4" > "lidarr_setup.sh"
	m4 "bin/ombi_setup.m4" > "ombi_setup.sh"
	m4 "bin/organizr_setup.m4" > "organizr_setup.sh"
	m4 "bin/plex_setup.m4" > "plex_setup.sh"
	m4 "bin/prowlarr_setup.m4" > "prowlarr_setup.sh"
	m4 "bin/radarr_setup.m4" > "radarr_setup.sh"
	m4 "bin/sabnzbd_setup.m4" > "sabnzbd_setup.sh"
	m4 "bin/sonarr_setup.m4" > "sonarr_setup.sh"
	m4 "bin/tautulli_setup.m4" > "tautulli_setup.sh"
	m4 "bin/torrents_setup.m4" > "torrents_setup.sh"
	m4 "bin/openvpn_ipfw.m4" > bin/openvpn_ipfw.rules
	m4 "bin/Freenas_13.x_Setup.m4" > "Freenas 13.x Setup.md"

clean :
	rm "Freenas 13.x Setup.md"
	rm "bazarr_setup.sh"
	rm "emby_setup.sh"
	rm "jellyfin_setup.sh"
	rm "lidarr_setup.sh"
	rm "ombi_setup.sh"
	rm "organizr_setup.sh"
	rm "plex_setup.sh"
	rm "prowlarr_setup.sh"
	rm "radarr_setup.sh"
	rm "sabnzbd_setup.sh"
	rm "sonarr_setup.sh"
	rm "tautulli_setup.sh"
	rm "torrents_setup.sh"
	rm "bin/openvpn_ipfw.rules"
